package topics.backtracking;

import java.util.stream.IntStream;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * <h1>Permutations Generation</h1>
 * <p>
 * This class exhaustively generates all possible permutations of an ordered 
 * mathematical set containing <i>N</i> distinct integer elements. It employs a 
 * <strong>Backtracking</strong> paradigm to construct valid sequences dynamically.
 * </p>
 *
 * <h2>Complexity</h2>
 * <ul>
 * <li><strong>Time Complexity:</strong> <code>O(N!)</code> - Generating all permutations of N elements requires factorial time, as the algorithm explores every unique arrangement across the state space tree.</li>
 * <li><strong>Space Complexity:</strong> <code>O(N)</code> - Requires linear space to store the domain vector, the boolean tracking array, the partial solution vector, and the activation records on the JVM stack.</li>
 * </ul>
 *
 * @author vicegd
 */
public class Permutations {
    private static final Logger log = LoggerFactory.getLogger(Permutations.class);

    private final int setSize;
    private final int[] elementDomain;
    private final int[] currentPermutation;
    private final boolean[] isElementUsed;
    private int permutationCount;

    /**
     * Initializes the state tracking structures to generate permutations 
     * for a set of integers from <code>0</code> to <code>N-1</code>.
     *
     * @param setSize The total number of elements (N) in the domain.
     */
    public Permutations(int setSize) {
        this.setSize = setSize;
        
        // Populate the domain with sequential integers [0, 1, 2, ..., N-1]
        this.elementDomain = IntStream.range(0, setSize).toArray();
        
        this.currentPermutation = new int[setSize];
        this.isElementUsed = new boolean[setSize];
        this.permutationCount = 0;
    }

    /**
     * Triggers the recursive backtracking engine to generate all permutations.
     */
    public void generateAll() {
        backtrack(0);
    }

    /**
     * The core recursive backtracking method that builds permutations element by element.
     *
     * @param depthLevel The current depth in the state space tree, representing the 
     * position in the permutation vector being filled.
     */
    private void backtrack(int depthLevel) {
        // Base Case: A complete permutation of size N has been assembled
        if (depthLevel == setSize) {
            permutationCount++;
            logSolution();
            return;
        }

        // Branching: Attempt to place every available element from the domain into the current depth
        for (int i = 0; i < setSize; i++) {
            // Feasibility Check: Only use elements that have not been selected higher up in the tree
            if (!isElementUsed[i]) {
                
                // Apply State Transition: Select the element and mark it as used
                currentPermutation[depthLevel] = elementDomain[i];
                isElementUsed[i] = true;
                
                // Recursive Descent: Move to the next slot in the permutation
                backtrack(depthLevel + 1);
                
                // Rollback (Pruning): Deselect the element to allow alternative branches
                currentPermutation[depthLevel] = -1;
                isElementUsed[i] = false;
            }
        }
    }

    /**
     * Formats and logs the fully constructed permutation vector.
     * <p>
     * String construction is bypassed if debug logging is disabled to preserve CPU cycles.
     * </p>
     */
    private void logSolution() {
        if (!log.isDebugEnabled()) {
            return;
        }
        
        var sb = new StringBuilder();
        for (int element : currentPermutation) {
            sb.append(element).append("*");
        }
        log.debug("{}", sb);
    }

    /**
     * Retrieves the total count of permutations generated by the algorithm.
     *
     * @return The integer count of valid permutations.
     */
    public int getPermutationCount() {
        return permutationCount;
    }
}